@startuml company

'公司
class 公司 {
    工商信息
    分析信息
    []公司关系
    []合同关系
    []公司成员
    []财务数据
    []股东信息
    []受益所有人
    []产品关系
    []公司发展
    []知识产权
    []历史信息
}

class 公司 #pink ##[bold]red

class 分析信息{
    分析状态
    []分析记录
}

分析信息 "1"-right-"*" 分析记录
class 分析记录 {
    记录人 string
    记录日期 datetime
    内容 string
}

class 工商信息{
    公司名称 string
    法定代表人 string
    统一社会信用代码 string
    注册资本 money
    实缴出资 money
    公司成立日期 datetime
    经营期限 int
    经营状态 string
    企业类型 string
    所属行业 string
    登记机关 string
    参保人数 int
    注册地址 string
    经营范围 string
    主营业务 string
}

class 公司关系{
    公司名称
    负责人
    地址
    联系人
    联系电话
    经营范围
    主营业务
}

class 合同关系{
     合同类型
     合同名称
     合同主体
     合同签订时间
     合同生效（履行）期间
     合同主要内容
     合同标的金额
     合同附件（上传）
}

class 公司成员{
    '@enum(法定代表人,董监高,重要人员)
    成员类型
}

class 财务数据{
    来源：数据库，文件
    财务标准格式？
}

class 股东信息{
    公司
    人员
}

class 股权代持{

}

class 产品关系{
}

class 受益所有人{
    名称（机构或自然人名称）
    法定代表人或负责人
    住址
    注册资本
    经营状态
    主营业务
    所有投资企业
    所有任职企业等。
}

公司 "1"-left-"*" 产品关系
公司 "1"-left-"*" 公司关系
公司 "1"-down-"*" 股东信息
公司 "1"-down-"*" 财务数据
公司 "1"-up-"*" 公司成员
公司 "1"-right-"*" 合同关系
公司 "1"-up-"*" 工商信息
公司 "1"-right-"1" 分析信息
公司 "1"-up-"*" 受益所有人
股权代持 "1"-up-"1" 股东信息



@enduml