@startuml person

skinparam nodesep 5

' 模型分析 @framework(es)
namespace person {

    top to bottom direction

    '人员
    ' @aggregatea
    class Person   {
        caseId string
        '基本信息
        basic  Basic
        '许可
        license []License
        '报案人金额
        reportMoney ReportMoney
        '嫌疑人金额
        suspectMoney SuspectMoney
        '地址
        address []Address
        '备忘录
        memos []Memo
    }

    '基本信息
    class Basic {
        name string
        birthday DateTime
        analyse string
        notes string
        '性别 @enum{Man:"男",Woman:"女",Unknown:"男"}
        gender Gender
        '人员类型 @enum{Informant:报案人,Suspect:嫌疑人,Victim:第三人,Third:第三人}
        peopleType PeopleType
        '分析类型 @enum{待分析,分析中,排除,完成}
        analyseStatus AnalyseStatus
    }

    '地址 @
    class Address {
        ' 省
        province string
        ' 市
        city string
        ' 区
        district string
        ' 详细
        detail string
    }

    '证件 @entity
    class Cert {
        '截止日期 @enum{IdCard:身份证,Drive:驾驶证,Health:医保,SocialSecurity:社保卡}
        type CertType
        '卡号
        code string
        '截止日期
        expDate dateTime
        '备注
        notes string
    }

    '嫌疑人金额 @entity
    class SuspectMoney {

    }
    ' 账户
    class Account {
        code string
        bank string
    }


    class Memo {
        userId string
        time dateTime
    }

    Person ”1“-up-"*" Cert :> 拥有
    Person ”1“-up-"1" Basic :> 拥有
    Person ”1“-up-"*" Address :> 拥有
    Person ”1“-left-"*" Account :> 拥有
    Person ”1“-right-"*" License :> 拥有
    Person -down- ReportMoney :> 拥有
    Person -down- SuspectMoney :> 拥有
}


@enduml

