@startuml person

skinparam nodesep 5

' 模型分析 @framework(es)
namespace person {

    top to bottom direction

    '人员
    ' @aggregatea
    class Person   {
        CaseId string
        '基本信息
        Basic  Basic
        '许可
        License[] License
        '报案人金额
        ReportMoney ReportMoney
        '嫌疑人金额
        SuspectMoney SuspectMoney
        '地址
        Address[] Address
    }

    '基本信息
    class Basic {
        Name string
        Birthday dateTime
        Analyse string
        Notes string
        '性别 @enum{Man:"男",Woman:"女",Unknown:"男"}
        Gender Gender
        '人员类型 @enum{Informant:报案人,Suspect:嫌疑人,Victim:第三人,Third:第三人}
        PeopleType PeopleType
        '分析类型 @enum{待分析,分析中,排除,完成}
        AnalyseStatus AnalyseStatus
    }

    '地址 @
    class Address {
        ' 省
        Province string
        ' 市
        City string
        ' 区
        District string
        ' 详细
        Detail string
    }

    '证件 @entity
    class Certificate {
        '截止日期 @enum{IdCard:身份证,Drive:驾驶证,Health:医保,SocialSecurity:社保卡}
        Type CertificateType
        '卡号
        Code string
        '截止日期
        ExpirationDate dateTime
        '备注
        Notes string
    }

    enum CertificateType {

    }

    '嫌疑人金额 @entity
    class SuspectMoney {

    }
    ' 账户
    class Account {
        Code string
        Bank string
    }
    Person ”1“-up-"1" Basic :> 拥有
    Person ”1“-up-"1" Address :> 拥有
    Person ”1“-left-"*" Account :> 拥有
    Person ”1“-right-"*" License :> 拥有
    Person -down- ReportMoney :> 拥有
    Person -down- SuspectMoney :> 拥有
}


@enduml

